<?php

namespace App\Http\Controllers\Orders;

use App\Enums\PaymentStatus;
use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Support\Facades\Storage;

class OrderReceiptController extends Controller
{
    // =========================================================================
    //  Serve the tax invoice PDF for a paid sales order.
    //
    //  Access rules:
    //    - Only the order owner can download
    //    - Only available for paid orders
    //    - Only available when KRA validation is complete (invoice_path set)
    //
    //  The invoice is generated by KraReceiptService when the SAP webhook
    //  delivers the CU number. Before that, no invoice exists.
    // =========================================================================

    public function __invoke(Order $order)
    {
        // Only the order owner can download their invoice
        abort_if($order->user_id !== auth()->id(), 403);

        // Invoice only available once payment is confirmed
        abort_if(
            $order->payment?->status?->value !== PaymentStatus::PAID->value,
            403,
            'Invoice is only available for paid orders.'
        );

        // Invoice only available after KRA validation
        abort_if(
            ! $order->hasKraReceipt(),
            403,
            'Invoice is pending KRA validation. Please check back shortly.'
        );

        // Serve from stored file
        if ($order->invoice_path && Storage::disk('local')->exists($order->invoice_path)) {
            return Storage::disk('local')->download(
                $order->invoice_path,
                "Invoice-{$order->reference}.pdf"
            );
        }

        // File missing — should not happen if hasKraReceipt() is true
        abort(404, 'Invoice file not found. Please contact support.');
    }
}
