// Sheffield — real product photography catalog. Each product maps to one or more images.
// Used by ProductIllustration when product.photos is present, and by ProductPage's gallery.

window.SHEFFIELD_PHOTOS = {
  "brema-cb-416-ice-cube":      ["assets/products/brema-cb416-ice.jpg"],
  "brema-cb-640-ice-cube":      ["assets/products/brema-cb640-ice.jpg"],
  "rancilio-classe-5-1gr":      ["assets/products/rancilio-classe-5-espresso.png"],
  "gn4100tn-4door-counter":     ["assets/products/gn4100tn-4door.jpg"],
  "snack3100tn-3door-counter":  ["assets/products/snack3100tn-3door.jpg"],
  "gn2100tng-glass-counter":    ["assets/products/gn2100tng-glass-1.jpg", "assets/products/gn2100tng-glass-2.jpg"],
};

window.SHEFFIELD_NEW_PRODUCTS = [
  {
    slug: "brema-cb-416-ice-cube",
    name: "Brema CB 416 Ice Cube Machine",
    sku: "BRE-CB-416",
    brand: "rational",
    category: "beverage_equipment",
    kind: "chiller",
    type: "simple",
    tagline: "Compact 25 kg/24h gourmet ice cube maker — bar, café and breakfast service.",
    price: 232000,
    compareAt: null,
    badge: "New",
    rating: 4.8, reviews: 48,
    inStock: 6, leadTime: "Ships in 3–5 days",
    images: 1, photos: ["assets/products/brema-cb416-ice.jpg"],
    power: "0.4 kW", capacity: "25 kg / 24h",
    weight: "39 kg", dimensions: "390 × 460 × 595 mm",
    warranty: "24 months parts & labour", origin: "Made in Villa Cortese, Italy",
    isNew: true, featured: false,
    specs: [
      { label: "Production",  value: "25 kg / 24h gourmet cubes" },
      { label: "Bin",         value: "8 kg integrated" },
      { label: "Refrigerant", value: "R290 (hydrocarbon)" },
      { label: "Connection",  value: "230 V · 50 Hz · 1.6 A" },
      { label: "Water",       value: "3/4″ inlet, gravity drain" },
    ],
    tags: ["Ice", "Bar"],
  },
  {
    slug: "brema-cb-640-ice-cube",
    name: "Brema CB 640 Ice Cube Machine",
    sku: "BRE-CB-640",
    brand: "rational",
    category: "beverage_equipment",
    kind: "chiller",
    type: "simple",
    tagline: "Workhorse 35 kg/24h ice cube maker with dual condenser intakes.",
    price: 318000,
    compareAt: null,
    badge: null,
    rating: 4.9, reviews: 31,
    inStock: 4, leadTime: "Ships in 3–5 days",
    images: 1, photos: ["assets/products/brema-cb640-ice.jpg"],
    power: "0.55 kW", capacity: "35 kg / 24h",
    weight: "53 kg", dimensions: "500 × 580 × 690 mm",
    warranty: "24 months parts & labour", origin: "Made in Villa Cortese, Italy",
    isNew: false, featured: true,
    specs: [
      { label: "Production",  value: "35 kg / 24h gourmet cubes" },
      { label: "Bin",         value: "12 kg integrated" },
      { label: "Refrigerant", value: "R290" },
      { label: "Connection",  value: "230 V · 50 Hz · 2.4 A" },
    ],
    tags: ["Ice", "Bar"],
  },
  {
    slug: "rancilio-classe-5-1gr",
    name: "Rancilio Classe 5 S — 1 Group Espresso Machine",
    sku: "RAN-C5S-1GR",
    brand: "rational",
    category: "coffee_machine",
    kind: "blender",
    type: "simple",
    tagline: "Compact commercial espresso for cafés, restaurants and offices — Italian-made.",
    price: 412000,
    compareAt: 445000,
    badge: "Save 7%",
    rating: 4.9, reviews: 124,
    inStock: 8, leadTime: "Ships in 5–7 days",
    images: 1, photos: ["assets/products/rancilio-classe-5-espresso.png"],
    power: "2.7 kW", capacity: "1 group · 5 L boiler",
    weight: "58 kg", dimensions: "450 × 555 × 545 mm",
    warranty: "24 months parts & labour", origin: "Made in Villastanza, Italy",
    isNew: true, featured: true,
    specs: [
      { label: "Groups",       value: "1 group · semi-automatic" },
      { label: "Boiler",       value: "5 L · copper" },
      { label: "Power",        value: "2.7 kW · 230 V" },
      { label: "Steam wands",  value: "1 stainless steel wand" },
      { label: "Filter",       value: "58 mm portafilter — industry standard" },
      { label: "Soft infusion","value": "Pre-infusion chamber for even extraction" },
    ],
    tags: ["Espresso", "1-group"],
  },
  {
    slug: "gn4100tn-4door-counter",
    name: "Sheffield GN 4100 TN — 4-Door Stainless Counter",
    sku: "SHF-GN4100-TN",
    brand: "true",
    category: "cold_displays",
    kind: "refrigerator",
    type: "simple",
    tagline: "Heavy-duty 4-door GN refrigerated prep counter. 553 L net, full-stainless construction.",
    price: 485000,
    compareAt: null,
    badge: "Bestseller",
    rating: 4.8, reviews: 96,
    inStock: 5, leadTime: "Ships in 3–5 days",
    images: 1, photos: ["assets/products/gn4100tn-4door.jpg"],
    power: "1/2 HP", capacity: "553 L · 4 GN doors",
    weight: "175 kg", dimensions: "2230 × 700 × 860 mm",
    warranty: "24 months parts & labour", origin: "Assembled in Italy",
    isNew: false, featured: true,
    specs: [
      { label: "Capacity",   value: "553 L net" },
      { label: "Doors",      value: "4 × solid stainless" },
      { label: "Temp range", value: "−2°C to +8°C" },
      { label: "Refrigerant", value: "R290" },
      { label: "Construction", value: "AISI 304 stainless inside & out" },
      { label: "Castors",    value: "4 heavy-duty, 2 with brake" },
    ],
    tags: ["Counter", "GN", "4-door"],
  },
  {
    slug: "snack3100tn-3door-counter",
    name: "Sheffield Snack 3100 TN — 3-Door Counter",
    sku: "SHF-SNACK3100-TN",
    brand: "true",
    category: "cold_displays",
    kind: "refrigerator",
    type: "variant",
    tagline: "Snack-line refrigerated counter. Available in 2-, 3- and 4-door configurations.",
    price: 348000,
    compareAt: null,
    badge: "Configurable",
    rating: 4.7, reviews: 64,
    inStock: 9, leadTime: "Ships in 3–5 days",
    images: 1, photos: ["assets/products/snack3100tn-3door.jpg"],
    power: "1/3 HP", capacity: "417 L · 3 doors",
    weight: "138 kg", dimensions: "1795 × 600 × 860 mm",
    warranty: "24 months parts & labour", origin: "Assembled in Italy",
    isNew: false, featured: false,
    variantAxes: [
      { id: "doors", label: "Doors", kind: "swatch", options: [
        { id: "2", label: "2-door", sub: "278 L · 1345 mm", diff: -68000 },
        { id: "3", label: "3-door", sub: "417 L · 1795 mm", diff: 0 },
        { id: "4", label: "4-door", sub: "553 L · 2230 mm", diff: 96000 },
      ]},
      { id: "top",   label: "Top finish", kind: "chip", options: [
        { id: "stainless", label: "Stainless", diff: 0 },
        { id: "granite",   label: "Granite",   diff: 24000 },
      ]},
    ],
    specs: [
      { label: "Capacity",   value: "278 / 417 / 553 L by configuration" },
      { label: "Temp range", value: "−2°C to +8°C" },
      { label: "Refrigerant", value: "R290" },
      { label: "Construction", value: "AISI 304 stainless" },
    ],
    tags: ["Counter", "Snack-line"],
  },
  {
    slug: "gn2100tng-glass-counter",
    name: "Sheffield GN 2100 TNG — Glass-Door Display Counter",
    sku: "SHF-GN2100-TNG",
    brand: "true",
    category: "cold_displays",
    kind: "refrigerator",
    type: "simple",
    tagline: "2-door glass display counter. Showcases beverages, garnishes and pastries under chilled temperature.",
    price: 392000,
    compareAt: null,
    badge: null,
    rating: 4.7, reviews: 38,
    inStock: 3, leadTime: "Ships in 4–6 days",
    images: 2, photos: ["assets/products/gn2100tng-glass-1.jpg", "assets/products/gn2100tng-glass-2.jpg"],
    power: "1/3 HP", capacity: "278 L · 2 glass doors",
    weight: "126 kg", dimensions: "1345 × 700 × 860 mm",
    warranty: "24 months parts & labour", origin: "Assembled in Italy",
    isNew: true, featured: false,
    specs: [
      { label: "Doors",     value: "2 × heated glass" },
      { label: "Capacity",  value: "278 L net" },
      { label: "Temp range", value: "+2°C to +10°C" },
      { label: "Lighting",  value: "Interior LED" },
      { label: "Refrigerant", value: "R290" },
    ],
    tags: ["Counter", "Glass-door", "Display"],
  },
];

(function () {
  const D = window.SHEFFIELD_DATA;
  if (!D) return;
  const existing = new Set(D.products.map(p => p.slug));
  for (const p of window.SHEFFIELD_NEW_PRODUCTS) {
    if (!existing.has(p.slug)) D.products.push(p);
  }

  // Also attach photos to a couple of existing products via the photos catalog (none currently overlap, but keep loop for future)
  for (const p of D.products) {
    if (!p.photos && window.SHEFFIELD_PHOTOS[p.slug]) p.photos = window.SHEFFIELD_PHOTOS[p.slug];
  }
})();
