// Sheffield — mock catalog data.
// Mix of restaurant, hotel and catering kitchen equipment.

window.SHEFFIELD_DATA = (function () {
  const KES = (n) => "KES\u00A0" + n.toLocaleString("en-KE");

  const categories = [
    { slug: "burners",             name: "Burners",             count: 64,  blurb: "Gas burners, ranges, salamanders and combi-steamers.",
      icon: "assets/categories/burners_icon.png",             image: "assets/categories/burners.webp" },
    { slug: "cold_displays",       name: "Cold Displays",       count: 96,  blurb: "Reach-in, undercounter, blast chillers and walk-in cold rooms.",
      icon: "assets/categories/cold_displays_icon.png",       image: "assets/categories/cold_displays.webp" },
    { slug: "bakery_preparation",  name: "Bakery Preparation",  count: 142, blurb: "Mixers, slicers, processors and dough prep stations.",
      icon: "assets/categories/bakery_preparation_icon.png",  image: "assets/categories/bakery_preparation.webp" },
    { slug: "dishwashers",         name: "Dishwashers",         count: 38,  blurb: "Glass, undercounter, hood and pass-through warewashing.",
      icon: "assets/categories/dishwashers_icon.png",         image: "assets/categories/dishwashers.webp" },
    { slug: "buffet_servery",      name: "Buffet & Servery",    count: 71,  blurb: "Chafing dishes, heated tops and servery counters.",
      icon: "assets/categories/buffet_servery_icon.png",      image: "assets/categories/buffet_servery.webp" },
    { slug: "coffee_machine",      name: "Coffee Machines",     count: 52,  blurb: "Espresso, bean-to-cup, filter brewers and grinders.",
      icon: "assets/categories/coffee_machine_icon.png",      image: "assets/categories/coffee_machine.webp" },
    { slug: "beverage_equipment",  name: "Beverage Equipment",  count: 48,  blurb: "Juicers, blenders, dispensers and ice machines.",
      icon: "assets/categories/beverage_equipment_icon.png",  image: "assets/categories/beverage_equipment.webp" },
    { slug: "cleaning_solutions",  name: "Cleaning Solutions",  count: 86,  blurb: "Floor scrubbers, vacuums and industrial cleaning.",
      icon: "assets/categories/cleaning_solutions_icon.png",  image: "assets/categories/cleaning_solutions.webp" },
    { slug: "hot_holding",         name: "Hot Holding",         count: 43,  blurb: "Bain-maries, heated cabinets and food holding stations.", icon: null, image: null },
    { slug: "ranges_ovens",        name: "Ranges & Ovens",      count: 78,  blurb: "Gas and electric ranges, deck ovens, convection ovens.",   icon: null, image: null },
    { slug: "ice_machines",        name: "Ice Machines",        count: 24,  blurb: "Cube, flake, nugget and scotsman ice production.",         icon: null, image: null },
    { slug: "smallwares",          name: "Smallwares",          count: 612, blurb: "Pots, pans, knives and serviceware.",                      icon: null, image: null },
  ];

  const brands = [
    { slug: "rational",     name: "Rational",     country: "Germany",       founded: 1973, blurb: "Combi-steamers and iVario multifunction cooking." },
    { slug: "hobart",       name: "Hobart",       country: "United States", founded: 1897, blurb: "Mixers, slicers and warewashing systems." },
    { slug: "true",         name: "True",         country: "United States", founded: 1945, blurb: "Commercial refrigeration since 1945." },
    { slug: "electrolux",   name: "Electrolux Professional", country: "Sweden", founded: 1919, blurb: "Full-line kitchen and laundry systems." },
    { slug: "lacanche",     name: "Lacanche",     country: "France",        founded: 1796, blurb: "Hand-built French cooking ranges." },
    { slug: "victorinox",   name: "Victorinox",   country: "Switzerland",   founded: 1884, blurb: "Knives and service smallwares." },
    { slug: "robot-coupe",  name: "Robot Coupe",  country: "France",        founded: 1961, blurb: "Food processors and prep machines." },
    { slug: "winterhalter", name: "Winterhalter", country: "Germany",       founded: 1947, blurb: "Warewash with reverse-osmosis dosing." },
  ];

  const products = [
    {
      slug: "rational-icombi-pro-6-1e",
      name: "Rational iCombi Pro 6-1/1 E",
      sku: "RAT-ICP-6-E",
      brand: "rational",
      category: "burners",
      kind: "combi-oven",
      tagline: "Six-grid electric combi-steamer with iCookingSuite intelligence.",
      price: 1485000,
      compareAt: null,
      badge: "Bestseller",
      rating: 4.9,
      reviews: 218,
      inStock: 12,
      leadTime: "Ships in 3–5 days",
      bulkPrice: { qty: 3, price: 1410000 },
      images: 5,
      power: "10.8 kW",
      capacity: "6 × GN 1/1",
      weight: "118 kg",
      dimensions: "847 × 776 × 782 mm",
      warranty: "24 months parts & labour",
      origin: "Made in Landsberg, Germany",
      featured: true,
      specs: [
        { label: "Grid capacity",  value: "6 × GN 1/1 (60–300 covers)" },
        { label: "Cooking modes",  value: "Steam, hot air, combination 30–300°C" },
        { label: "Connected load", value: "10.8 kW · 400 V 3N~ 50 Hz" },
        { label: "Water connection", value: "R 3/4″ cold + soft" },
        { label: "Drain",          value: "DN 50, max 95°C" },
        { label: "Net weight",     value: "118 kg" },
        { label: "Cabinet",        value: "1.4301 stainless steel" },
        { label: "iCookingSuite",  value: "Yes — 7 cooking processes" },
        { label: "ConnectedCooking", value: "WiFi & LAN ready" },
        { label: "HACCP logging",  value: "Built-in, USB export" },
      ],
      tags: ["iCombi", "Bake", "Steam", "Grill", "Roast"],
    },
    {
      slug: "true-t-49-2-door-refrigerator",
      name: "True T-49 Two-Section Reach-In Refrigerator",
      sku: "TRU-T49-HC",
      brand: "true",
      category: "cold_displays",
      kind: "refrigerator",
      tagline: "Hydrocarbon refrigerant, 49 cu ft, NSF certified.",
      price: 685000,
      compareAt: 745000,
      badge: "Save 8%",
      rating: 4.8,
      reviews: 162,
      inStock: 7,
      leadTime: "Ships in 5–7 days",
      bulkPrice: { qty: 5, price: 645000 },
      images: 4,
      power: "1/3 HP",
      capacity: "49 cu ft / 1388 L",
      weight: "186 kg",
      dimensions: "1372 × 768 × 2080 mm",
      warranty: "36 months parts & 60 months compressor",
      origin: "Made in O'Fallon, Missouri",
      featured: true,
      specs: [
        { label: "Capacity",       value: "49 cu ft · 1388 L" },
        { label: "Refrigerant",    value: "R290 (hydrocarbon)" },
        { label: "Temp range",     value: "+1°C to +4°C" },
        { label: "Compressor",     value: "1/3 HP, oversized" },
        { label: "Shelving",       value: "6 PVC-coated, adjustable" },
        { label: "Interior",       value: "Stainless 304" },
        { label: "Door type",      value: "Solid, self-closing, 90° stay-open" },
        { label: "Power",          value: "230 V · 50 Hz" },
        { label: "Energy use",     value: "8.4 kWh / 24h" },
        { label: "Certifications", value: "NSF · ENERGY STAR" },
      ],
      tags: ["Reach-in", "R290", "ENERGY STAR"],
    },
    {
      slug: "hobart-hl600-60qt-mixer",
      name: "Hobart Legacy HL600 60-Quart Mixer",
      sku: "HOB-HL600",
      brand: "hobart",
      category: "bakery_preparation",
      kind: "mixer",
      tagline: "Floor-standing planetary mixer for bakeries and high-output kitchens.",
      price: 1120000,
      compareAt: null,
      badge: null,
      rating: 4.9,
      reviews: 89,
      inStock: 3,
      leadTime: "Ships in 7–10 days",
      bulkPrice: null,
      images: 4,
      power: "2.7 hp",
      capacity: "60 qt / 57 L",
      weight: "278 kg",
      dimensions: "688 × 838 × 1391 mm",
      warranty: "12 months parts & labour",
      origin: "Made in Troy, Ohio",
      featured: true,
      specs: [
        { label: "Bowl capacity",  value: "60 qt · 57 L" },
        { label: "Motor",          value: "2.7 hp continuous duty" },
        { label: "Speeds",         value: "4-speed, gear-driven" },
        { label: "Bowl lift",      value: "Manual lever" },
        { label: "Attachments",    value: "Beater, whip, dough hook (#12 hub)" },
        { label: "Construction",   value: "Cast iron body, stainless trim" },
        { label: "Power",          value: "230 V 3-phase · 50 Hz" },
        { label: "Shipping wt.",   value: "278 kg" },
        { label: "Certifications", value: "NSF · UL · CE" },
      ],
      tags: ["Planetary", "Bakery", "60qt"],
    },
    {
      slug: "winterhalter-um-passthrough",
      isNew: true,
      name: "Winterhalter UC-M Pass-Through Dishwasher",
      sku: "WIN-UCM-PT",
      brand: "winterhalter",
      category: "dishwashers",
      kind: "dishwasher",
      tagline: "Hood-type warewasher with integrated reverse osmosis.",
      price: 945000,
      compareAt: null,
      badge: "New",
      rating: 4.7,
      reviews: 64,
      inStock: 5,
      leadTime: "Ships in 4–6 days",
      bulkPrice: null,
      images: 4,
      power: "12 kW",
      capacity: "60 racks/h",
      weight: "148 kg",
      dimensions: "635 × 740 × 1480 mm",
      warranty: "24 months parts & labour",
      origin: "Made in Meckenbeuren, Germany",
      featured: false,
      specs: [
        { label: "Cycle times",    value: "60 / 120 / 240 s" },
        { label: "Throughput",     value: "Up to 60 racks/h" },
        { label: "Rack size",      value: "500 × 500 mm" },
        { label: "Connected load", value: "12 kW · 400 V 3N~ 50 Hz" },
        { label: "Wash temp",      value: "62°C" },
        { label: "Rinse temp",     value: "85°C" },
        { label: "Soft-start",     value: "Yes" },
        { label: "Heat recovery",  value: "Optional, recovers up to 4 kW" },
      ],
      tags: ["Pass-through", "RO", "Heat-recovery"],
    },
    {
      slug: "lacanche-cluny-1400-range",
      name: "Lacanche Cluny 1400 Cooking Range",
      sku: "LAC-CLUNY-1400",
      brand: "lacanche",
      category: "burners",
      kind: "range",
      tagline: "Hand-built dual-fuel range — six burners, two ovens.",
      price: 2480000,
      compareAt: null,
      badge: "Made to order",
      rating: 5.0,
      reviews: 41,
      inStock: 0,
      leadTime: "Built to order — 10 weeks",
      bulkPrice: null,
      images: 6,
      power: "9.6 kW gas + 2.4 kW elec.",
      capacity: "6 burners, 2 ovens",
      weight: "245 kg",
      dimensions: "1400 × 700 × 920 mm",
      warranty: "24 months · lifetime burner",
      origin: "Hand-built in Bourgogne, France",
      featured: true,
      specs: [
        { label: "Configuration",  value: "6 burners + 2 ovens" },
        { label: "Fuel",           value: "Dual fuel (gas top, electric ovens)" },
        { label: "Top output",     value: "4 × 3.5 kW + 2 × 5 kW burners" },
        { label: "Main oven",      value: "73 L convection · 50–280°C" },
        { label: "Aux oven",       value: "32 L static · 50–280°C" },
        { label: "Finish",         value: "26 enamel colours, brass or chrome trim" },
        { label: "Cast iron grates", value: "Continuous, single-piece" },
        { label: "Lead time",      value: "10 weeks made-to-order" },
      ],
      tags: ["Range", "Dual-fuel", "Made-to-order", "Heritage"],
    },
    {
      slug: "robot-coupe-r502-processor",
      name: "Robot Coupe R502 Combination Food Processor",
      sku: "RC-R502",
      brand: "robot-coupe",
      category: "bakery_preparation",
      kind: "processor",
      tagline: "Bowl-cutter plus continuous vegetable prep — 250–300 covers.",
      price: 385000,
      compareAt: 420000,
      badge: "Save 8%",
      rating: 4.7,
      reviews: 113,
      inStock: 9,
      leadTime: "Ships next day",
      bulkPrice: { qty: 3, price: 365000 },
      images: 4,
      power: "1.5 hp",
      capacity: "5.5 L bowl",
      weight: "26 kg",
      dimensions: "350 × 590 × 530 mm",
      warranty: "12 months",
      origin: "Made in Vincennes, France",
      featured: true,
      specs: [
        { label: "Bowl",           value: "5.5 L stainless cutter" },
        { label: "Hopper",         value: "Continuous feed with 2 inlets" },
        { label: "Speed",          value: "1500 rpm · single speed" },
        { label: "Motor",          value: "1.5 hp asynchronous, induction" },
        { label: "Discs supplied", value: "4 (slice 2/4 mm, grate 2/4 mm)" },
        { label: "Pulse function", value: "Yes" },
        { label: "Power",          value: "230 V · 50 Hz" },
      ],
      tags: ["Cutter-mixer", "Veg-prep"],
    },
    {
      slug: "electrolux-blast-chiller-bce5",
      isNew: true,
      name: "Electrolux SkyLine PremiumS Blast Chiller",
      sku: "ELX-BCE5-S",
      brand: "electrolux",
      category: "cold_displays",
      kind: "chiller",
      tagline: "5-tray blast chiller and shock-freezer with multi-point probe.",
      price: 875000,
      compareAt: null,
      badge: "HACCP",
      rating: 4.8,
      reviews: 52,
      inStock: 4,
      leadTime: "Ships in 6–8 days",
      bulkPrice: null,
      images: 5,
      power: "2.1 kW",
      capacity: "5 × GN 1/1 / 18 kg",
      weight: "115 kg",
      dimensions: "750 × 800 × 850 mm",
      warranty: "24 months parts & labour",
      origin: "Made in Vallenoncello, Italy",
      featured: false,
      specs: [
        { label: "Capacity",       value: "5 × GN 1/1 · +90°C → +3°C in 90 min" },
        { label: "Freeze cycle",   value: "+90°C → -18°C in 240 min" },
        { label: "Probe",          value: "Multi-point 6-sensor, USB export" },
        { label: "Refrigerant",    value: "R452A" },
        { label: "Cabinet",        value: "AISI 304 stainless" },
        { label: "HACCP",          value: "Built-in 12-month log" },
      ],
      tags: ["Blast-chill", "Shock-freeze", "HACCP"],
    },
    {
      slug: "hobart-edge-13-slicer",
      name: "Hobart Edge 13″ Manual Slicer",
      sku: "HOB-EDGE13",
      brand: "hobart",
      category: "bakery_preparation",
      kind: "slicer",
      tagline: "Belt-driven manual slicer — deli, charcuterie, prep.",
      price: 198000,
      compareAt: null,
      badge: null,
      rating: 4.6,
      reviews: 137,
      inStock: 14,
      leadTime: "Ships next day",
      bulkPrice: { qty: 4, price: 188000 },
      images: 4,
      power: "1/3 hp",
      capacity: "13″ blade",
      weight: "31 kg",
      dimensions: "600 × 540 × 480 mm",
      warranty: "12 months",
      origin: "Made in Troy, Ohio",
      featured: false,
      specs: [
        { label: "Blade",          value: "13″ hollow-ground, hard-chrome" },
        { label: "Drive",          value: "Belt drive, 1/3 hp" },
        { label: "Slice thickness",value: "0 – 19 mm" },
        { label: "Construction",   value: "Anodized aluminum body, stainless trim" },
        { label: "Sharpener",      value: "Built-in dual-stone, removable" },
        { label: "Power",          value: "230 V · 50 Hz" },
      ],
      tags: ["Slicer", "Deli"],
    },
    {
      slug: "true-tcgg-50-display-case",
      name: "True TCGG-50 Curved-Glass Refrigerated Display",
      sku: "TRU-TCGG-50",
      brand: "true",
      category: "buffet_servery",
      kind: "display",
      tagline: "Pastry & deli display with three angled shelves.",
      price: 495000,
      compareAt: null,
      badge: null,
      rating: 4.7,
      reviews: 76,
      inStock: 6,
      leadTime: "Ships in 5–7 days",
      bulkPrice: null,
      images: 4,
      power: "1/2 HP",
      capacity: "50″ / 1270 mm",
      weight: "118 kg",
      dimensions: "1270 × 815 × 1280 mm",
      warranty: "24 months parts & labour",
      origin: "Made in O'Fallon, Missouri",
      featured: true,
      specs: [
        { label: "Length",         value: "1270 mm / 50″" },
        { label: "Temp range",     value: "+1°C to +7°C" },
        { label: "Shelving",       value: "3 angled, LED-lit" },
        { label: "Refrigerant",    value: "R290" },
        { label: "Lighting",       value: "Top-mount LED, dim 0–100%" },
      ],
      tags: ["Display", "Pastry", "LED"],
    },
    {
      slug: "victorinox-fibrox-chef-25cm",
      name: "Victorinox Fibrox Pro 25 cm Chef's Knife",
      sku: "VIC-FIBROX-25",
      brand: "victorinox",
      category: "bakery_preparation",
      kind: "knife",
      tagline: "NSF-certified chef's knife — the kitchen workhorse.",
      price: 8900,
      compareAt: null,
      badge: null,
      rating: 4.9,
      reviews: 1842,
      inStock: 320,
      leadTime: "Ships same day",
      bulkPrice: { qty: 12, price: 7900 },
      images: 3,
      power: null,
      capacity: "25 cm blade",
      weight: "0.21 kg",
      dimensions: "395 × 35 × 22 mm",
      warranty: "Lifetime against manufacturer defect",
      origin: "Made in Ibach, Switzerland",
      featured: false,
      specs: [
        { label: "Blade length",   value: "25 cm" },
        { label: "Steel",          value: "X50CrMoV15 stainless" },
        { label: "Edge",           value: "Hand-finished, ~15° per side" },
        { label: "Handle",         value: "Fibrox, slip-resistant" },
        { label: "Certifications", value: "NSF" },
      ],
      tags: ["Knife", "Chef"],
    },
    {
      slug: "rational-ivario-pro-l",
      isNew: true,
      name: "Rational iVario Pro L Multifunction Pan",
      sku: "RAT-IVR-L",
      brand: "rational",
      category: "burners",
      kind: "tilting-pan",
      tagline: "Boil, fry, deep-fry and pressure-cook — one platform.",
      price: 1985000,
      compareAt: null,
      badge: "iVario",
      rating: 4.9,
      reviews: 67,
      inStock: 2,
      leadTime: "Ships in 8–10 days",
      bulkPrice: null,
      images: 5,
      power: "17 kW",
      capacity: "100 L",
      weight: "215 kg",
      dimensions: "1100 × 928 × 1080 mm",
      warranty: "24 months parts & labour",
      origin: "Made in Landsberg, Germany",
      featured: false,
      specs: [
        { label: "Pan capacity",   value: "100 L / 2 × 50 L split" },
        { label: "Cooking surface",value: "70 dm² · ceramic-coated" },
        { label: "Temperature",    value: "30 – 250°C in 2.5 min" },
        { label: "Pressure cook",  value: "Optional, up to 2 bar" },
        { label: "Connected load", value: "17 kW · 400 V 3N~" },
        { label: "Tilt",           value: "Motorized, auto-empty" },
      ],
      tags: ["iVario", "Tilting", "Pressure"],
    },
    {
      slug: "robot-coupe-mp-450-blender",
      isNew: true,
      name: "Robot Coupe MP 450 Immersion Blender",
      sku: "RC-MP450",
      brand: "robot-coupe",
      category: "bakery_preparation",
      kind: "blender",
      tagline: "Variable-speed power mixer for 50–100 L stockpots.",
      price: 86500,
      compareAt: null,
      badge: null,
      rating: 4.8,
      reviews: 211,
      inStock: 22,
      leadTime: "Ships same day",
      bulkPrice: null,
      images: 3,
      power: "440 W",
      capacity: "50–100 L pot",
      weight: "5.2 kg",
      dimensions: "150 × 150 × 808 mm",
      warranty: "12 months",
      origin: "Made in Vincennes, France",
      featured: false,
      specs: [
        { label: "Motor",          value: "440 W variable-speed" },
        { label: "Speed range",    value: "1500 – 13000 rpm" },
        { label: "Shaft length",   value: "450 mm" },
        { label: "Pot range",      value: "50 – 100 L" },
        { label: "Construction",   value: "Stainless, removable foot" },
      ],
      tags: ["Stick", "Variable-speed"],
    },
  ];

  return { categories, brands, products, KES };
})();
